#!/usr/bin/env python3
import sys


def solve(S: str):
    ret = ""
    for s in reversed(S):
        if s == "6":
            ret += "9"
        elif s == "9":
            ret += "6"
        else:
            ret += s
    print(ret)
    return


# Generated by 2.3.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    S = next(tokens)  # type: str
    solve(S)

if __name__ == '__main__':
    main()
