#!/usr/bin/env python3
import sys


def solve(N: int, A: "List[int]"):
    A = list(map(lambda x: x % 200, A))
    ret = 0
    for i in range(200):
        same = 0
        for num in A:
            if num == i:
                same += 1
        ret += int(same * (same - 1) / 2)
    print(ret)
    return


# Generated by 2.3.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    A = [int(next(tokens)) for _ in range(N)]  # type: "List[int]"
    solve(N, A)

if __name__ == '__main__':
    main()
