#!/usr/bin/env python3
import sys

YES = "Yes"  # type: str
NO = "No"  # type: str


def solve(N: int, K: int, A: "List[int]", B: "List[int]"):
    diff = 0
    for i in range(N):
        diff += abs(A[i] - B[i])

    if diff > K:
        print(NO)
        return

    aIsOdd = sum(A) % 2 == 0
    bIsOdd = sum(B) % 2 == 0
    if (aIsOdd == bIsOdd):
        if K % 2 == 0:
            print(YES)
        else:
            print(NO)
    else:
        if K % 2 != 0:
            print(YES)
        else:
            print(NO)
    return


# Generated by 2.3.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    K = int(next(tokens))  # type: int
    A = [int(next(tokens)) for _ in range(N)]  # type: "List[int]"
    B = [int(next(tokens)) for _ in range(N)]  # type: "List[int]"
    solve(N, K, A, B)

if __name__ == '__main__':
    main()
