#!/usr/bin/env python3
import sys


def solve(S: str):
    count = 0
    for i in range(10000):
        if judge(str(i).zfill(4), S):
            count += 1
    print(count)
    return

def judge(t: str, S: str):
    for i in range(len(S)):
        if S[i] == "o" and not(str(i) in t):
            return False
        elif S[i] == "x" and (str(i) in t):
            return False
    return True


# Generated by 2.3.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    S = next(tokens)  # type: str
    solve(S)

if __name__ == '__main__':
    main()
